name: epub
version: 1.0.0
author: Colin Nelson <colin@ifdevthentalk.com>
description: Epub Parser for Dart
homepage: https://github.com/orthros/dart-epub
environment:
  sdk: '>=1.13.2 <2.0.0'
dependencies:
  async: ^1.13.2
  archive: ^1.0.28
  xml: ^2.5.0
  image: ^1.1.26
dev_dependencies:  
  scheduled_test: '^0.12.0'
  test: '^0.12.7'
  path: any