name: epub
version: 1.2.5
author: Colin Nelson <colinnlsn@gmail.com>
description: Epub Parser for Dart. Suitable for use on the Web or in Flutter 
homepage: https://github.com/orthros/dart-epub
environment:
  sdk: ">=1.21.0 <=2.0.0"
dependencies:
  async: "^1.8.0"
  archive: "^1.0.33"
  xml: "^2.6.0"
  image: "^1.1.29"
dev_dependencies:  
  scheduled_test: "^0.12.0"
  test: "^0.12.0"
  path: "^1.5.1"
